"""Tests for the app-DB engine/migration plumbing (src/db/engine.py, migrations/).

Covers: `alembic upgrade head` against a fresh database actually creates every W5 table (a
real exercise of the migration path, not just a diff against the ORM metadata it was
autogenerated from — the two could otherwise silently drift if a migration were hand-edited
without updating the model, or vice versa), that the migrated schema has *zero* structural
diff against the ORM metadata (table names alone aren't enough to catch a dropped column or
constraint — W5_review.md MINOR-2), the default (unconfigured) database URL never resolves
under data/ — that directory is the platform seam owned by neither peer (data/CONTRACT.md,
docs/website_production_overview.md §3), and that SQLite foreign keys are actually enforced at
runtime, not just declared (W5_review.md LOW-3).
"""
from pathlib import Path

import pytest
from alembic import command
from alembic.autogenerate import compare_metadata
from alembic.config import Config
from alembic.runtime.migration import MigrationContext
from sqlalchemy import create_engine, inspect
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import sessionmaker

from src.db.engine import build_engine, resolve_database_url
from src.db.models import Base, Membership

_PLATE_COST_DIR = Path(__file__).resolve().parents[1]

_EXPECTED_TABLES = {
    "restaurants", "users", "memberships", "credentials", "sessions", "staged_uploads", "dishes",
}


def test_alembic_upgrade_head_creates_all_w5_tables(tmp_path, monkeypatch):
    db_path = tmp_path / "migration_test.db"
    monkeypatch.setenv("ONRAMP_DATABASE_URL", f"sqlite:///{db_path}")

    cfg = Config(str(_PLATE_COST_DIR / "alembic.ini"))
    cfg.set_main_option("script_location", str(_PLATE_COST_DIR / "migrations"))
    command.upgrade(cfg, "head")

    engine = create_engine(f"sqlite:///{db_path}")
    tables = set(inspect(engine).get_table_names())
    engine.dispose()

    assert _EXPECTED_TABLES <= tables


def test_migrated_schema_matches_orm_metadata_exactly(tmp_path, monkeypatch):
    """The rest of the suite builds its schema via ``Base.metadata.create_all`` (conftest.py),
    never through the migration — so a model change with no matching migration (or a
    hand-edited migration that drifts from the model) would pass every other test silently.
    This runs the *actual* migration against a throwaway DB and diffs the result against the
    ORM metadata that's supposed to be its single source of truth; an empty diff is the only
    passing result (W5_review.md MINOR-2 — table-name-only checks like the test above aren't
    enough to catch a dropped column, type change, or missing constraint)."""
    db_path = tmp_path / "drift_check.db"
    monkeypatch.setenv("ONRAMP_DATABASE_URL", f"sqlite:///{db_path}")

    cfg = Config(str(_PLATE_COST_DIR / "alembic.ini"))
    cfg.set_main_option("script_location", str(_PLATE_COST_DIR / "migrations"))
    command.upgrade(cfg, "head")

    engine = create_engine(f"sqlite:///{db_path}")
    with engine.connect() as connection:
        context = MigrationContext.configure(connection)
        diff = compare_metadata(context, Base.metadata)
    engine.dispose()

    assert diff == [], f"migration/ORM drift detected: {diff}"


def test_build_engine_enables_sqlite_foreign_key_enforcement(tmp_path):
    """SQLite ignores every declared ``ForeignKey`` unless ``PRAGMA foreign_keys=ON`` is set per
    connection — off by default in sqlite3. Without ``build_engine`` turning it on, the FKs in
    ``src/db/models.py`` are documentation, not a runtime guard (W5_review.md LOW-3)."""
    db_path = tmp_path / "fk_check.db"
    engine = build_engine(f"sqlite:///{db_path}")
    Base.metadata.create_all(engine)
    factory = sessionmaker(bind=engine, autoflush=False, expire_on_commit=False)

    session = factory()
    session.add(Membership(user_id="no-such-user", restaurant_id="no-such-restaurant", role="owner"))
    with pytest.raises(IntegrityError):
        session.commit()
    session.close()
    engine.dispose()


def test_default_database_url_never_resolves_under_the_seam(monkeypatch):
    monkeypatch.delenv("ONRAMP_DATABASE_URL", raising=False)
    url = resolve_database_url()

    assert url.startswith("sqlite:///")
    db_path = Path(url[len("sqlite:///"):]).resolve()
    seam_dir = (_PLATE_COST_DIR.parent.parent / "data").resolve()

    assert seam_dir != db_path and seam_dir not in db_path.parents


def test_env_var_database_url_takes_priority_over_the_default(monkeypatch):
    monkeypatch.setenv("ONRAMP_DATABASE_URL", "sqlite:////tmp/somewhere-else.db")
    assert resolve_database_url() == "sqlite:////tmp/somewhere-else.db"
